version: '3'
services:
  app:
    image: dyoshikawa/laravel:latest
    volumes:
      - .:/myproject:cached
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: dyoshikawa/mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
    volumes:
      - ./mysql-data:/var/lib/mysql:cached
    ports:
      - 3306:3306
