version: '3'
services:
  app:
    image: dyoshikawa/laravel:latest
    volumes:
      - .:/myproject:cached
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: dyoshikawa/mysql:latest
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./mysql-data:/var/lib/mysql/data:cached
    ports:
      - 5432:5432
