version: '3'
services:
  app:
    image: dyoshikawa/laravel:latest
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: password
