version: '3'
services:
  app:
    image: dyoshikawa/laravel:latest
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
